kit_news_list:
    path:     /
    defaults: { _controller: KitNewsBundle:Default:index }
kit_news_add:
    path:     /add
    defaults: { _controller: KitNewsBundle:Default:add }
kit_news_classify:
    path:     /classify
    defaults: { _controller: KitNewsBundle:Classify:index }
kit_news_classify_add:
    path:     /classify/add
    defaults: { _controller: KitNewsBundle:Classify:add }