kit_news_list:
    path:     /
    defaults: { _controller: KitNewsBundle:Default:index }
kit_news_add:
    path:     /add
    defaults: { _controller: KitNewsBundle:Default:add }
kit_news_category:
    path:     /category
    defaults: { _controller: KitNewsBundle:Category:index }
kit_news_category_add:
    path:     /category/add
    defaults: { _controller: KitNewsBundle:Category:add }