kit_news_list:
    path:     /
    defaults: { _controller: KitNewsBundle:Default:index }
kit_news_add:
    path:     /add
    defaults: { _controller: KitNewsBundle:Default:add }
kit_news_category:
    path:     /category/{page}
    defaults: { _controller: KitNewsBundle:Category:index, page: 1 }
    requirements:
        page: '\d+'
kit_news_category_add:
    path:     /category/add
    defaults: { _controller: KitNewsBundle:Category:add }
kit_news_category_update:
    path:     /category/update/{id}
    defaults: { _controller: KitNewsBundle:Category:update }
    requirements:
        id: '\d+'