kit_web:
    resource: "@KitWebBundle/Resources/config/routing.yml"
    prefix:   /

kit_backup:
    resource: "@KitBackupBundle/Resources/config/routing.yml"
    prefix:   /backup

kit_api:
    resource: "@KitApiBundle/Resources/config/routing.yml"
    prefix:   /api

kit_settings:
    resource: "@KitSettingsBundle/Resources/config/routing.yml"
    prefix:   /setting

kit_archive:
    resource: "@KitArchiveBundle/Resources/config/routing.yml"
    prefix:   /archive

kit_inquire:
    resource: "@KitInquireBundle/Resources/config/routing.yml"
    prefix:   /inquire

kit_analysis:
    resource: "@KitAnalysisBundle/Resources/config/routing.yml"
    prefix:   /analysis

kit_warning:
    resource: "@KitWarningBundle/Resources/config/routing.yml"
    prefix:   /warning

kit_monitor:
    resource: "@KitMonitorBundle/Resources/config/routing.yml"
    prefix:   /monitor

kit_menu:
    resource: "@KitMenuBundle/Resources/config/routing.yml"
    prefix:   /menu

kit_case:
    resource: "@KitCaseBundle/Controller/"
    type:     annotation
    prefix:   /case

kit_user:
    resource: "@KitUserBundle/Controller/"
    type:     annotation
    prefix:   /user

kit_news:
    resource: "@KitNewsBundle/Resources/config/routing.yml"
    prefix:   /admin/news

kit_admin:
    resource: "@KitAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

kit_rbac:
    resource: "@KitRbacBundle/Resources/config/routing.yml"
    prefix:   /admin/rbac

kit_base:
    resource: "@KitBaseBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /