kit_menu:
    resource: "@KitMenuBundle/Resources/config/routing.yml"
    prefix:   /

kit_case:
    resource: "@KitCaseBundle/Controller/"
    type:     annotation
    prefix:   /

kit_user:
    resource: "@KitUserBundle/Controller/"
    type:     annotation
    prefix:   /

kit_news:
    resource: "@KitNewsBundle/Resources/config/routing.yml"
    prefix:   /

kit_admin:
    resource: "@KitAdminBundle/Resources/config/routing.yml"
    prefix:   /

kit_base:
    resource: "@KitBaseBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"