kit_settings:
    resource: "@KitSettingsBundle/Resources/config/routing.yml"
    prefix:   /

kit_archive:
    resource: "@KitArchiveBundle/Resources/config/routing.yml"
    prefix:   /

kit_inquire:
    resource: "@KitInquireBundle/Resources/config/routing.yml"
    prefix:   /

kit_analysis:
    resource: "@KitAnalysisBundle/Resources/config/routing.yml"
    prefix:   /

kit_warning:
    resource: "@KitWarningBundle/Resources/config/routing.yml"
    prefix:   /

kit_monitor:
    resource: "@KitMonitorBundle/Resources/config/routing.yml"
    prefix:   /

kit_menu:
    resource: "@KitMenuBundle/Resources/config/routing.yml"
    prefix:   /

kit_case:
    resource: "@KitCaseBundle/Controller/"
    type:     annotation
    prefix:   /

kit_user:
    resource: "@KitUserBundle/Controller/"
    type:     annotation
    prefix:   /

kit_news:
    resource: "@KitNewsBundle/Resources/config/routing.yml"
    prefix:   /

kit_admin:
    resource: "@KitAdminBundle/Resources/config/routing.yml"
    prefix:   /

kit_base:
    resource: "@KitBaseBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"