# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
# security:

#     # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         # disables authentication for assets and the profiler, adapt it according to your needs
#         dev:
#             pattern: ^/(_(profiler|wdt)|css|images|js)/
#             security: false

#         main:
#             anonymous: ~
#             # activate different ways to authenticate

#             # http_basic: ~
#             # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

#             # form_login: ~
#             # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        KitAdminBundle\Security\User\WebserviceUser:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        webservice:
            id: app.webservice_user_provider
        fos_userbundle:
            id: fos_user.user_provider.username
        kit_api_provider:
            entity:
                class: KitAdminBundle:ApiUser
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            http_basic:
                provider: kit_api_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin/, role: ROLE_ADMIN }
