<?php

namespace KitVideoBundle\Repository;

/**
 * VideoLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoLogRepository extends \Doctrine\ORM\EntityRepository
{
}
