kit_video_homepage:
    path:     /video
    defaults: { _controller: KitVideoBundle:Default:index }
kit_video_log:
    resource: "@KitVideoBundle/Resources/config/routing/videolog.yml"
    prefix:   /videolog
