<?php

namespace Kit\SettingsBundle\Repository;

/**
 * OfficeAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
