videolog_index:
    path:     /
    defaults: { _controller: "KitVideoBundle:VideoLog:index" }
    methods:  GET

videolog_show:
    path:     /{id}/show
    defaults: { _controller: "KitVideoBundle:VideoLog:show" }
    methods:  GET

videolog_new:
    path:     /new
    defaults: { _controller: "KitVideoBundle:VideoLog:new" }
    methods:  [GET, POST]

videolog_edit:
    path:     /{id}/edit
    defaults: { _controller: "KitVideoBundle:VideoLog:edit" }
    methods:  [GET, POST]

videolog_delete:
    path:     /{id}/delete
    defaults: { _controller: "KitVideoBundle:VideoLog:delete" }
    methods:  DELETE
