<?php

namespace KitAdminBundle\Repository;

/**
 * AdminGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
