<?php

namespace KitHouseBundle\Repository;

/**
 * HouseAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
