<?php

namespace KitHouseBundle\Repository;

/**
 * HouseAlbumItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseAlbumItemRepository extends \Doctrine\ORM\EntityRepository
{
}
