<?php

namespace KitRbacBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($status = false, $page = false, $pagesize = false)
    {
        $queryBuilder = $this->createQueryBuilder('u');
        return $queryBuilder->select();
    }
}
