<?php

namespace KitNewsBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getParentClassify()
    {
        return $this->createQueryBuilder('c')
                    ->select('c.id', 'c.name')
                    ->where('c.pid = 0')
                    ->andWhere('c.status = 1')
                    ->orderBy('c.id', 'DESC');
    }
}
