<?php

namespace KitNewsBundle\Repository;

/**
 * ClassifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifyRepository extends \Doctrine\ORM\EntityRepository
{
}
