kit_web_homepage:
    path:     /
    defaults: { _controller: KitWebBundle:Default:index }
kit_web_news:
    path:     /news
    defaults: { _controller: KitWebBundle:News:index }
kit_web_news_list:
    path:     /news/list
    defaults: { _controller: KitWebBundle:News:list }
kit_web_news_jscroll:
    path:     /news/jscroll
    defaults: { _controller: KitWebBundle:News:jscroll }
kit_web_news_show:
    path:     /news/show/{uuid}
    defaults: { _controller: KitWebBundle:News:show }
kit_web_news_data:
    path:     /news/data
    defaults: { _controller: KitWebBundle:News:data }
kit_web_user:
    path:     /u
    defaults: { _controller: KitWebBundle:User:index }
kit_web_login:
    path:     /login
    defaults: { _controller: KitWebBundle:User:login }
kit_web_login_check:
    path:     /login_check
    defaults: { _controller: KitWebBundle:User:login_check }
kit_web_logout:
    path:     /logout
    defaults: { _controller: KitWebBundle:User:logout }
kit_web_register:
    path:     /register
    defaults: { _controller: KitWebBundle:User:register }
kit_web_test_update:
    path:     /NewKwGameBox/getGameBoxUpdateInfo
    defaults: { _controller: KitWebBundle:Test:index }