kit_dnspod_homepage:
    path:     /
    defaults: { _controller: KitDnspodBundle:Default:index }
kit_dnspod_version:
    path:     /version
    defaults: { _controller: KitDnspodBundle:Default:version }
kit_dnspod_user:
    path:     /user
    defaults: { _controller: KitDnspodBundle:Default:user }
kit_dnspod_log:
    path:     /log
    defaults: { _controller: KitDnspodBundle:Default:log }
kit_dnspod_domain:
    path:     /domain/list/{page}
    defaults: { _controller: KitDnspodBundle:Domain:list, page:1 }
    requirements:
        page: '\d+'
kit_dnspod_domain_group:
    path:     /domain/group/{page}
    defaults: { _controller: KitDnspodBundle:Domain:group, page:1 }
    requirements:
        page: '\d+'
kit_dnspod_record:
    path:     /record/{page}
    defaults: { _controller: KitDnspodBundle:Record:index, page:1 }
    requirements:
        page: '\d+'
kit_dnspod_record_create:
    path:     /record/create
    defaults: { _controller: KitDnspodBundle:Record:create }
kit_dnspod_record_add:
    path:     /record/add
    defaults: { _controller: KitDnspodBundle:Record:add }
