<?php

namespace Kit\CaseBundle\Repository;

/**
 * CaseFeebackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseFeebackRepository extends \Doctrine\ORM\EntityRepository
{
}
