<?php

namespace Kit\CaseBundle\Repository;

/**
 * CaseRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
